addSbtPlugin("com.jsuereth"      %  "sbt-pgp"         % "1.1.0")
addSbtPlugin("de.heikoseeberger" %  "sbt-header"      % "4.1.0")
addSbtPlugin("org.xerial.sbt"    %  "sbt-sonatype"    % "2.0")
addSbtPlugin("com.typesafe.sbt"  %  "sbt-git"         % "0.9.3")
addSbtPlugin("com.typesafe"      %  "sbt-mima-plugin" % "0.1.18")
