addSbtPlugin("com.jsuereth"      %  "sbt-pgp"         % "1.1.2")
addSbtPlugin("com.jsuereth"      %  "sbt-pgp"         % "2.0.1")
addSbtPlugin("de.heikoseeberger" %  "sbt-header"      % "5.4.0")
addSbtPlugin("org.xerial.sbt"    %  "sbt-sonatype"    % "3.9.2")
addSbtPlugin("com.typesafe.sbt"  %  "sbt-git"         % "1.0.0")
addSbtPlugin("com.typesafe"      %  "sbt-mima-plugin" % "0.7.0")
addSbtPlugin("org.scoverage"     %  "sbt-scoverage"   % "1.6.1")
addSbtPlugin("org.scalameta"        % "sbt-scalafmt"    % "2.3.2")